version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: graphql
    versions:
    - 1.11.6
    - 1.12.5
    - 1.12.6
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: geocoder
    versions:
    - 1.6.4
    - 1.6.5
    - 1.6.6
  - dependency-name: loofah
    versions:
    - 2.9.0
